# Generated by Django 5.2.17 on 2026-09-27 12:49

import campings.models
import core.fields
import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Part of the address of your public page. Lowercase letters, numbers and hyphens.",
                        max_length=80,
                        unique=True,
                        verbose_name="web address",
                    ),
                ),
                (
                    "tagline",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        help_text="A short sentence shown under the name.",
                        max_chars=180,
                        verbose_name="tagline",
                    ),
                ),
                (
                    "description",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        textarea=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "location_info",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        help_text="Surroundings, distances, directions, public transport...",
                        textarea=True,
                        verbose_name="location and how to get there",
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="category (stars)",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="International format, e.g. +34600111222.",
                        max_length=40,
                        verbose_name="WhatsApp",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="town / city"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="region / province"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "open_all_year",
                    models.BooleanField(default=False, verbose_name="open all year"),
                ),
                (
                    "opening_date",
                    models.DateField(
                        blank=True,
                        help_text="Only the day and month are used: it repeats every year.",
                        null=True,
                        verbose_name="opening date",
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True,
                        help_text="Last day of departure. It repeats every year.",
                        null=True,
                        verbose_name="closing date",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("en", "English"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                            ("nl", "Nederlands"),
                            ("it", "Italiano"),
                        ],
                        default="es",
                        max_length=10,
                        verbose_name="main language",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=campings.models.default_languages,
                        verbose_name="content languages",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR €"),
                            ("GBP", "GBP £"),
                            ("USD", "USD $"),
                            ("CHF", "CHF"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2f6f4e",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a colour code like #2f6f4e."
                            )
                        ],
                        verbose_name="main colour",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#e9a23b",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a colour code like #2f6f4e."
                            )
                        ],
                        verbose_name="accent colour",
                    ),
                ),
                (
                    "font_style",
                    models.CharField(
                        choices=[
                            ("modern", "Modern (sans-serif)"),
                            ("classic", "Classic (serif)"),
                            ("rounded", "Friendly (rounded)"),
                        ],
                        default="modern",
                        max_length=20,
                        verbose_name="typography",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=campings.models.logo_upload_to,
                        verbose_name="logo",
                    ),
                ),
                (
                    "accepts_booking_requests",
                    models.BooleanField(
                        default=True, verbose_name="accept booking requests"
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Where new booking requests are notified. Defaults to the contact e-mail.",
                        max_length=254,
                        verbose_name="e-mail for booking requests",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Only approved campings can be seen by the public.",
                        verbose_name="approved by the platform",
                    ),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. www.mycamping.com. Point its DNS to the platform first.",
                        max_length=253,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(?=.{1,253}$)(?!-)([a-z0-9-]{1,63}(?<!-)\\.)+[a-z]{2,63}$",
                                "Enter a domain such as www.mycamping.com (without https://).",
                            )
                        ],
                        verbose_name="own domain",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "camping",
                "verbose_name_plural": "campings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_from",
                    models.TimeField(
                        default=datetime.time(14, 0), verbose_name="check-in from"
                    ),
                ),
                (
                    "check_in_until",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(21, 0),
                        null=True,
                        verbose_name="check-in until",
                    ),
                ),
                (
                    "check_out_until",
                    models.TimeField(
                        default=datetime.time(12, 0), verbose_name="check-out until"
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="minimum nights",
                    ),
                ),
                (
                    "max_nights",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="maximum nights"
                    ),
                ),
                (
                    "min_age",
                    models.PositiveSmallIntegerField(
                        default=18, verbose_name="minimum age of the person booking"
                    ),
                ),
                (
                    "deposit_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percentage of the total requested to confirm a booking. 0 = no deposit.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="deposit to confirm (%)",
                    ),
                ),
                (
                    "refundable",
                    models.BooleanField(
                        default=True, verbose_name="cancellations allowed"
                    ),
                ),
                (
                    "free_cancellation_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        verbose_name="free cancellation until (days before arrival)",
                    ),
                ),
                (
                    "cancellation_fee_percent",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="fee for later cancellations (%)",
                    ),
                ),
                (
                    "pets_allowed",
                    models.BooleanField(default=True, verbose_name="pets allowed"),
                ),
                (
                    "quiet_hours_from",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(23, 0),
                        null=True,
                        verbose_name="quiet hours from",
                    ),
                ),
                (
                    "quiet_hours_until",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(8, 0),
                        null=True,
                        verbose_name="quiet hours until",
                    ),
                ),
                (
                    "payment_methods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="payment methods"
                    ),
                ),
                (
                    "cancellation_text",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        textarea=True,
                        verbose_name="cancellation details",
                    ),
                ),
                (
                    "payment_text",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        textarea=True,
                        verbose_name="payment details",
                    ),
                ),
                (
                    "pets_text",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        textarea=True,
                        verbose_name="pet policy",
                    ),
                ),
                (
                    "rules_text",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        textarea=True,
                        verbose_name="camping rules",
                    ),
                ),
                (
                    "camping",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="campings.camping",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking policy",
                "verbose_name_plural": "booking policies",
            },
        ),
        migrations.CreateModel(
            name="AccommodationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pitch", "Pitch"),
                            ("bungalow", "Bungalow"),
                            ("mobile_home", "Mobile home"),
                            ("cabin", "Wooden cabin"),
                            ("glamping", "Glamping tent"),
                            ("tent_rental", "Rental tent"),
                            ("caravan_rental", "Rental caravan"),
                            ("apartment", "Apartment"),
                            ("room", "Room"),
                            ("other", "Other"),
                        ],
                        default="pitch",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "name",
                    core.fields.TranslatedField(
                        blank=True, default=dict, max_chars=120, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        textarea=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="maximum guests",
                    ),
                ),
                (
                    "size_m2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="size (m²)"
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="bedrooms"
                    ),
                ),
                (
                    "units",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many of these you have. Used to check availability.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="units available",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="amenities"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Used when no seasonal price is defined.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="base price",
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        choices=[
                            ("night", "per night"),
                            ("person_night", "per person / night"),
                        ],
                        default="night",
                        max_length=20,
                        verbose_name="price applies",
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="minimum nights"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="campings.camping",
                    ),
                ),
            ],
            options={
                "verbose_name": "accommodation type",
                "verbose_name_plural": "accommodation types",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=campings.models.photo_upload_to, verbose_name="image"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=campings.models.photo_upload_to,
                        verbose_name="thumbnail",
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0, editable=False)),
                ("height", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "caption",
                    core.fields.TranslatedField(
                        blank=True, default=dict, max_chars=200, verbose_name="caption"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "accommodation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Show this photo on an accommodation type as well.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="campings.accommodationtype",
                        verbose_name="accommodation",
                    ),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="campings.camping",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "verbose_name_plural": "photos",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    core.fields.TranslatedField(
                        blank=True, default=dict, max_chars=60, verbose_name="name"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="from")),
                ("end_date", models.DateField(verbose_name="to (inclusive)")),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional minimum stay for arrivals in this season.",
                        null=True,
                        verbose_name="minimum nights",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3f8f6b",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a colour code like #2f6f4e."
                            )
                        ],
                        verbose_name="colour",
                    ),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="campings.camping",
                    ),
                ),
            ],
            options={
                "verbose_name": "season",
                "verbose_name_plural": "seasons",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    core.fields.TranslatedField(
                        blank=True, default=dict, max_chars=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        max_chars=300,
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("tag", "Generic"),
                            ("user", "Adult"),
                            ("baby", "Child"),
                            ("dog", "Pet"),
                            ("car", "Car"),
                            ("motorbike", "Motorbike"),
                            ("tent", "Tent"),
                            ("caravan", "Caravan"),
                            ("van", "Camper van / motorhome"),
                            ("plug-zap", "Electricity"),
                            ("receipt", "Tax"),
                            ("bed", "Bed linen"),
                            ("shirt", "Towels"),
                            ("spray-can", "Cleaning"),
                            ("coffee", "Breakfast"),
                            ("clock", "Late check-out"),
                            ("bike", "Bike"),
                            ("users", "Visitor"),
                            ("refrigerator", "Fridge"),
                            ("flame", "Barbecue"),
                        ],
                        default="tag",
                        max_length=30,
                        verbose_name="icon",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="base price",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("night", "per night"),
                            ("stay", "per stay"),
                            ("adult_night", "per adult / night"),
                            ("child_night", "per child / night"),
                            ("person_night", "per person / night"),
                            ("person_stay", "per person / stay"),
                            ("pet_night", "per pet / night"),
                        ],
                        default="night",
                        max_length=20,
                        verbose_name="price unit",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("optional", "Optional extra (the guest chooses it)"),
                            ("mandatory", "Always charged (e.g. people, tourist tax)"),
                            ("included", "Included / information only"),
                        ],
                        default="optional",
                        max_length=20,
                        verbose_name="how it is charged",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "accommodations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply it to every accommodation type.",
                        related_name="services",
                        to="campings.accommodationtype",
                        verbose_name="applies to",
                    ),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="campings.camping",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services and extras",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reception_24h", "24-hour reception"),
                            ("wifi", "Wi-Fi"),
                            ("restaurant", "Restaurant"),
                            ("bar", "Bar"),
                            ("supermarket", "Supermarket"),
                            ("bakery", "Fresh bread"),
                            ("takeaway", "Takeaway food"),
                            ("laundry", "Laundry"),
                            ("fridge_rental", "Fridge rental"),
                            ("safe", "Safe deposit boxes"),
                            ("atm", "Cash machine"),
                            ("first_aid", "First aid"),
                            ("pool", "Swimming pool"),
                            ("kids_pool", "Children's pool"),
                            ("heated_pool", "Heated indoor pool"),
                            ("playground", "Playground"),
                            ("kids_club", "Kids club"),
                            ("entertainment", "Entertainment programme"),
                            ("sports_ground", "Sports ground"),
                            ("tennis", "Tennis / padel"),
                            ("gym", "Gym"),
                            ("spa", "Spa & wellness"),
                            ("games_room", "Games room"),
                            ("bike_rental", "Bike rental"),
                            ("water_sports", "Water sports"),
                            ("bbq", "Barbecue area"),
                            ("hot_showers", "Hot showers"),
                            ("toilets", "Toilet blocks"),
                            ("accessible", "Accessible facilities"),
                            ("baby_room", "Baby changing room"),
                            ("dishwashing", "Dishwashing area"),
                            ("electricity", "Electrical hook-up"),
                            ("water_points", "Drinking water points"),
                            ("motorhome_service", "Motorhome service area"),
                            ("chemical_disposal", "Chemical toilet disposal"),
                            ("shade", "Shaded pitches"),
                            ("parking", "Parking"),
                            ("ev_charging", "EV charging point"),
                            ("pets", "Pets welcome"),
                            ("dog_area", "Dog park / dog shower"),
                            ("beach", "Beach nearby"),
                            ("river", "River or lake"),
                            ("mountain", "Mountain setting"),
                            ("hiking", "Hiking trails"),
                            ("town", "Town nearby"),
                            ("public_transport", "Public transport"),
                            ("custom", "Custom"),
                        ],
                        max_length=40,
                        verbose_name="facility",
                    ),
                ),
                (
                    "name",
                    core.fields.TranslatedField(
                        blank=True, default=dict, max_chars=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    core.fields.TranslatedField(
                        blank=True,
                        default=dict,
                        help_text="Opening hours, season, conditions...",
                        max_chars=300,
                        verbose_name="details",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sparkles", "Generic"),
                            ("tent", "Tent"),
                            ("trees", "Nature"),
                            ("sun", "Sun"),
                            ("utensils", "Food"),
                            ("music", "Music"),
                            ("ticket", "Activities"),
                            ("heart", "Wellness"),
                            ("map", "Excursions"),
                            ("store", "Shop"),
                            ("wine", "Wine & drinks"),
                            ("footprints", "Walks"),
                        ],
                        max_length=40,
                        verbose_name="icon",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="extra charge"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="campings.camping",
                    ),
                ),
            ],
            options={
                "verbose_name": "facility",
                "verbose_name_plural": "facilities",
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "custom"), _negated=True),
                        fields=("camping", "kind"),
                        name="unique_facility_kind",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("staff", "Staff")],
                        default="owner",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="campings.camping",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "ordering": ["camping", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "camping"), name="unique_membership"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccommodationRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="campings.accommodationtype",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_rates",
                        to="campings.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "seasonal price",
                "verbose_name_plural": "seasonal prices",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("accommodation", "season"),
                        name="unique_accommodation_rate",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_rates",
                        to="campings.season",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="campings.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "seasonal service price",
                "verbose_name_plural": "seasonal service prices",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "season"), name="unique_service_rate"
                    )
                ],
            },
        ),
    ]
