# Generated by Django 5.2.17 on 2026-09-27 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camping",
            name="domain_verified_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="domain working since",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="show_platform_credit",
            field=models.BooleanField(
                default=True,
                help_text="“Powered by” link in the footer of the camping's website.",
                verbose_name="show the platform credit",
            ),
        ),
        migrations.AlterField(
            model_name="camping",
            name="slug",
            field=models.SlugField(
                help_text="Part of the address of your public page. Lowercase letters, numbers and hyphens.",
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$",
                        "Use lowercase letters, numbers and hyphens (up to 63 characters, not starting or ending with a hyphen).",
                    )
                ],
                verbose_name="web address",
            ),
        ),
    ]
