# Generated by Django 5.2.17 on 2026-09-28 06:01

import core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campings", "0003_season_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="camping",
            name="ga_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="G-XXXXXXXXXX. Only loaded when the visitor accepts statistics cookies.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^G-[A-Z0-9]{4,16}$",
                        "Use the measurement ID of Google Analytics 4, e.g. G-AB12CD34EF.",
                    )
                ],
                verbose_name="Google Analytics measurement ID",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="legal_address",
            field=models.CharField(
                blank=True,
                help_text="Leave it empty if it is the camping's address.",
                max_length=255,
                verbose_name="registered address",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Company or person that owns the camping.",
                max_length=200,
                verbose_name="legal name",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="legal_notice_extra",
            field=core.fields.TranslatedField(
                blank=True,
                default=dict,
                textarea=True,
                verbose_name="additional legal notice text",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="privacy_extra",
            field=core.fields.TranslatedField(
                blank=True,
                default=dict,
                textarea=True,
                verbose_name="additional privacy text",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="registry_info",
            field=models.CharField(
                blank=True,
                help_text="E.g. Registro Mercantil de Girona, tomo 1234, folio 56, hoja GI-7890.",
                max_length=300,
                verbose_name="company registry",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="search_console_verification",
            field=models.CharField(
                blank=True,
                help_text="The content of the google-site-verification meta tag.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9_-]{10,100}$",
                        'Paste only the code from the content="..." part.',
                    )
                ],
                verbose_name="Google Search Console verification code",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="NIF / CIF / VAT number.",
                max_length=30,
                verbose_name="tax ID",
            ),
        ),
        migrations.AddField(
            model_name="camping",
            name="tourism_registration",
            field=models.CharField(
                blank=True,
                help_text="Registration number in the regional tourism register, shown in the footer.",
                max_length=60,
                verbose_name="tourism registration number",
            ),
        ),
    ]
