# Generated by Django 5.2.17 on 2026-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                ("content", models.BinaryField(verbose_name="content")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="content type"),
                ),
                ("size", models.PositiveIntegerField(default=0, verbose_name="size")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
            ],
            options={
                "verbose_name": "stored file",
                "verbose_name_plural": "stored files",
            },
        ),
    ]
