# Generated by Django 5.2.17 on 2026-09-27 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campings", "0003_season_periods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="website")),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Ready to review"), ("applied", "Imported")],
                        default="ready",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("photo_queue", models.JSONField(blank=True, default=list)),
                ("photos_done", models.PositiveIntegerField(default=0)),
                ("photos_failed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_imports",
                        to="campings.camping",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "website import",
                "verbose_name_plural": "website imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
