# Generated by Django 5.2.17 on 2026-09-27 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="reference",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "accommodation_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="accommodation name"
                    ),
                ),
                ("arrival", models.DateField(verbose_name="arrival")),
                ("departure", models.DateField(verbose_name="departure")),
                (
                    "adults",
                    models.PositiveSmallIntegerField(default=2, verbose_name="adults"),
                ),
                (
                    "children",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="children"
                    ),
                ),
                (
                    "pets",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pets"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="country"),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "language",
                    models.CharField(
                        default="es", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "quote",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="price estimate"
                    ),
                ),
                (
                    "estimated_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="estimated total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="internal notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="received"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "accommodation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_requests",
                        to="campings.accommodationtype",
                        verbose_name="accommodation",
                    ),
                ),
                (
                    "camping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_requests",
                        to="campings.camping",
                    ),
                ),
                (
                    "extras",
                    models.ManyToManyField(
                        blank=True, to="campings.service", verbose_name="extras"
                    ),
                ),
            ],
            options={
                "verbose_name": "booking request",
                "verbose_name_plural": "booking requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["camping", "status", "arrival"],
                        name="bookings_bo_camping_e882e3_idx",
                    )
                ],
            },
        ),
    ]
