# Generated by Django 5.2.17 on 2026-09-27 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="source",
            field=models.CharField(
                choices=[("web", "Website"), ("manual", "Added in the panel")],
                default="web",
                max_length=10,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="units",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many units of this accommodation the stay takes up.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="units",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
    ]
